# Generated by Django 3.0.5 on 2020-11-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_auto_20201122_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='response',
            field=models.CharField(choices=[('warm', 'warm'), ('normal', 'normal'), ('cold', 'cold')], default='cold', max_length=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], default='others', max_length=10),
        ),
    ]
