# Generated by Django 3.0.5 on 2020-11-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_remove_category_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=10),
        ),
    ]
