# Generated by Django 3.0.5 on 2020-11-24 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0011_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
