# Generated by Django 3.0.8 on 2020-11-27 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0012_remove_customer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('time', models.TimeField(auto_now=True)),
                ('price', models.IntegerField(default=10)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Employee')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Product')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Service')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('number', models.CharField(max_length=10, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Employee')),
                ('slip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.Slip')),
            ],
        ),
    ]
