# Generated by Django 3.0.8 on 2020-11-27 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0013_bill_client_slip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slip',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.Product'),
        ),
        migrations.AlterField(
            model_name='slip',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.Service'),
        ),
    ]
