# Generated by Django 3.0.8 on 2020-11-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0014_auto_20201127_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='slip',
        ),
        migrations.AddField(
            model_name='bill',
            name='slip',
            field=models.ManyToManyField(to='basic.Slip'),
        ),
    ]
