# Generated by Django 3.0.8 on 2020-11-27 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0017_remove_slip_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slip',
            name='qty',
        ),
    ]
