# Generated by Django 3.0.8 on 2020-12-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0020_customer_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
