# Generated by Django 3.0.8 on 2020-12-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0021_client_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slip',
            name='product',
        ),
        migrations.AddField(
            model_name='slip',
            name='product',
            field=models.ManyToManyField(to='basic.Product'),
        ),
        migrations.RemoveField(
            model_name='slip',
            name='service',
        ),
        migrations.AddField(
            model_name='slip',
            name='service',
            field=models.ManyToManyField(to='basic.Service'),
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
